# Generated by Django 3.1 on 2020-09-04 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cocktailAPI',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
